/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    DCollapse: typeof import('vue-devui/collapse/index.es.js')['Collapse']
    DIcon: typeof import('vue-devui/icon/index.es.js')['Icon']
    DTooltip: typeof import('vue-devui/tooltip/index.es.js')['Tooltip']
  }
}
